;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Position.ValueChanged",NewTagName="Position.Player0")
+GameplayTagRedirects=(OldTagName="Game.StartRace",NewTagName="Game.CountdownEnded")
+GameplayTagList=(Tag="Game.CountdownEnded",DevComment="")
+GameplayTagList=(Tag="Game.TogglePause",DevComment="")
+GameplayTagList=(Tag="Position",DevComment="")

